[package]
name = "bun_which"
version = "0.1.1"
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[lib]
path = "lib.rs"

[lints]
workspace = true

[dependencies]
phf.workspace = true
bstr.workspace = true
bun_core.workspace = true
bun_paths.workspace = true
bun_sys.workspace = true
