[package]
name = "bun_transpiler"
version = "0.1.5"
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
bun_bundler = { path = "../bundler", version = "0.1.0" }
swc_common = { version = "23.0.1", features = ["tty-emitter"] }
swc_ecma_ast = "25.0.0"
swc_ecma_codegen = "28.0.1"
swc_ecma_parser = { version = "41.1.0", features = ["typescript"] }
swc_ecma_transforms_base = "44.0.2"
swc_ecma_transforms_typescript = "49.0.0"
swc_ecma_visit = "25.0.0"
