[package]
name = "bun_clap"
version = "0.1.3"
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[lib]
path = "lib.rs"

[lints]
workspace = true

[dependencies]
strum.workspace = true
phf.workspace = true
bstr.workspace = true
thiserror.workspace = true
bun_clap_macros.workspace = true
bun_core.workspace = true
