[package]
name = "bun_boringssl_sys"
version = "0.1.1"
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[lib]
path = "lib.rs"

[lints]
workspace = true

[build-dependencies]
cc = "1"

[dependencies]
bun_opaque.workspace = true
phf.workspace = true
bun_core.workspace = true

