[package]
name = "bun_boringssl"
version = "0.1.8"
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[lib]
path = "lib.rs"

[lints]
workspace = true

[dependencies]
phf.workspace = true
scopeguard.workspace = true
bun_alloc.workspace = true
bun_core.workspace = true
bun_sys.workspace = true
bun_boringssl_sys.workspace = true
bun_cares_sys.workspace = true
