[package]
name = "bao_browser"
version = "0.1.0"
edition = "2021"

[dependencies]
servo = { path = "../../vendor/servo/components/servo", default-features = false, features = ["baked-in-resources"] }
servo-url = { path = "../../vendor/servo/components/url" }
dpi = "0.1"
url = "2"
dashmap.workspace = true
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp"] }
base64 = "0.22"
serde_json = "1"
bao_cdp = { path = "../bao_cdp" }
bao_cdp_client = { path = "../bao_cdp_client" }
bao_stealth = { path = "../bao_stealth" }
bao_engine = { path = "../bao_engine" }
bun_runtime.workspace = true
bun_http.workspace = true
cdp-server = { path = "../cdp-server" }
bun_core.workspace = true
bun_sys.workspace = true
mozjs = { path = "../../vendor/mozjs/mozjs" }
serde = "1"
cookie = { package = "cookie", version = "0.18" }
log = "0.4"
euclid = "0.22"

[dev-dependencies]
bao_engine = { path = "../bao_engine" }
