[package]
name = "bun_js_printer"
# 0.1.1 (2026-08-19): W3 parser trio dual-mode (e00e3dcb)
version = "0.1.8"
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[lib]
path = "lib.rs"

[lints]
workspace = true

[dependencies]
bytemuck = "1"
strum.workspace = true
phf.workspace = true
bstr.workspace = true
scopeguard.workspace = true
const_format.workspace = true
enum-map.workspace = true
enumset.workspace = true
bumpalo.workspace = true
bun_alloc.workspace = true
bun_core.workspace = true
bun_ptr.workspace = true
bun_collections.workspace = true
bun_wyhash.workspace = true
bun_crash_handler.workspace = true
bun_io.workspace = true
bun_ast.workspace = true
bun_sourcemap.workspace = true
bun_options_types.workspace = true
bun_paths.workspace = true
bun_sys.workspace = true
