[package]
name = "bun_output"
version = "0.1.7"
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
bun_core = { path = "../bun_core", version = "0.1.0" }
