[package]
name = "bao_stealth"
version = "0.1.0"
edition = "2021"

[dependencies]
bao_engine = { path = "../bao_engine", version = "0.1.0" }
bun_core.workspace = true
bun_sha_hmac = { path = "../sha_hmac", version = "0.1.0" }
mozjs.workspace = true
mozjs_sys.workspace = true
dashmap.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
bun_runtime.workspace = true
