[package]
name = "bun_s3_signing"
version = "0.1.5"
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[lib]
path = "lib.rs"

[lints]
workspace = true

[dependencies]
strum.workspace = true
phf.workspace = true
bstr.workspace = true
libc.workspace = true
bitflags.workspace = true
thiserror.workspace = true
bun_base64.workspace = true
bun_core.workspace = true
bun_collections.workspace = true
bun_http_types.workspace = true
bun_picohttp.workspace = true
bun_ptr.workspace = true
bun_sha_hmac.workspace = true
bun_wyhash.workspace = true
