[package]
name = "bun_exe_format"
version = "0.1.6"
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[lib]
path = "lib.rs"

[lints]
workspace = true

[dependencies]
bytemuck = "1"
thiserror.workspace = true
strum.workspace = true
phf.workspace = true
bstr.workspace = true
bun_core.workspace = true
bun_sha_hmac.workspace = true
bun_sys.workspace = true
