[package]
name = "bun_dotenv"
# 0.1.1 (2026-08-19): ChanVec/VecExt sweep
version = "0.1.4"
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[lib]
path = "lib.rs"

[lints]
workspace = true

[dependencies]
phf.workspace = true
bstr.workspace = true
enumset.workspace = true
bun_alloc.workspace = true
bun_core.workspace = true
bun_collections.workspace = true
bun_ast.workspace = true
bun_paths.workspace = true
bun_sys.workspace = true
bun_url.workspace = true
bun_which.workspace = true
