#!/usr/bin/env bash
# scripts/ensure-codegen.sh — generate the Bao codegen stubs if missing.
#
# bun_core/build.rs requires build/<profile>/codegen/*.rs to exist (Bun upstream
# generates them via `bun bd --configure-only`, which runs TypeScript codegen).
# In Bao's SpiderMonkey migration these are deterministic stubs (JSC-specific
# codegen is unused), so we synthesize them here instead of depending on a Bun
# bootstrap. Idempotent: only writes files that are missing.
#
# Env:
#   BUN_CODEGEN_DIR  — override the output dir (default: $REPO/build/debug/codegen)
#                      Must match what bun_core/build.rs reads.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
CODEGEN_DIR="${BUN_CODEGEN_DIR:-$REPO/build/debug/codegen}"
mkdir -p "$CODEGEN_DIR"

# build_options.rs — build constants (deterministic dev defaults).
if [ ! -f "$CODEGEN_DIR/build_options.rs" ]; then
  cat > "$CODEGEN_DIR/build_options.rs" <<'RUST'
// Auto-generated build_options.rs for Bao development builds.
// In Bun upstream, this file is generated by scripts/build/buildOptionsRs.ts.

pub const SHA: &str = "0000000000000000000000000000000000000000";
pub const IS_CANARY: bool = false;
pub const CANARY_REVISION: &str = "";
pub const BASELINE: bool = false;
pub const RELEASE_SAFE: bool = false;
pub const ENABLE_LOGS: bool = false;
pub const ENABLE_ASAN: bool = false;
pub const ENABLE_FUZZILLI: bool = false;
pub const ENABLE_TINYCC: bool = false;
pub const REPORTED_NODEJS_VERSION: &str = "22.14.0";
pub const BASE_PATH: &[u8] = b"/usr/local";
pub const CODEGEN_PATH: &[u8] = b"build/debug/codegen";
pub const FALLBACK_HTML_VERSION: &str = "0.0.0-dev";
pub const VERSION: crate::Version = crate::Version {
    major: 0,
    minor: 0,
    patch: 0,
};
RUST
  echo "generated build_options.rs"
fi

# SpiderMonkey-migration stubs: JSC-specific codegen is unused in Bao.
declare -A STUBS=(
  ["cpp.rs"]="// Bao stub: JSC→SM migration, cpp.rs codegen not needed."
  ["generated_classes.rs"]="// Bao stub: JSC→SM migration, generated_classes not needed."
  ["generated_host_exports.rs"]="// Bao stub: host exports not used in SpiderMonkey mode."
  ["generated_js2native.rs"]="// Bao stub: JS2Native not used in SpiderMonkey mode."
  ["generated_jssink.rs"]="// Bao stub: JSSink not used in SpiderMonkey mode."
)
for name in "${!STUBS[@]}"; do
  if [ ! -f "$CODEGEN_DIR/$name" ]; then
    printf '%s\n' "${STUBS[$name]}" > "$CODEGEN_DIR/$name"
    echo "generated $name"
  fi
done

# generated_resolved_source_tag.rs — needs a real const (referenced by code).
if [ ! -f "$CODEGEN_DIR/generated_resolved_source_tag.rs" ]; then
  cat > "$CODEGEN_DIR/generated_resolved_source_tag.rs" <<'RUST'
// Bao stub: ResolvedSourceTag not used in SpiderMonkey mode.
pub const INTERNAL_MODULE_TAG: &[(&str, u32)] = &[];
RUST
  echo "generated generated_resolved_source_tag.rs"
fi

echo "codegen dir ready: $CODEGEN_DIR"
