#!/usr/bin/env bash
#
# scripts/native-deps-inventory.sh — W23-③ native dependency inventory
# (#18-③;single source of truth for the native-library contract).
#
# Three mechanical sources are reconciled into docs/native-deps.md:
#   1. doctor.rs `system_lib_check(label, pc_name, linked_by, apt_pkg)` table
#      — the RUNTIME check face;
#   2. musl-p5-consumer-closure.sh APK_SET — the musl (apk) face;
#   3. `links = "…"` declarations across src/ Cargo.tomls (currently exactly
#      one: libuv_sys → uv) — the cargo manifest face.
#
# The gate (default mode) asserts the DOCTOR↔DOC bidirectional diff = 0:
# every system_lib_check row must have a docs/native-deps.md row and vice
# versa (api-surface doc-lock philosophy). The apk/brew columns are
# informational (musl-p5 APK_SET / ci-slim brew precedent) — drift there is
# a NOTE, not red.
#
# Usage:
#   scripts/native-deps-inventory.sh --check     # gate (default): diff=0 → 0
#   scripts/native-deps-inventory.sh --update    # rewrite docs/native-deps.md
#   scripts/native-deps-inventory.sh --help
#
# W23-③ boundary note: doctor.rs itself is product code — this script never
# edits it; a doctor-side gap is reported RED for a separate fix contract.

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"

DOCTOR="src/bao_cli/src/doctor.rs"
DOC="docs/native-deps.md"
MUSL_SH="scripts/musl-p5-consumer-closure.sh"

mode="${1:---check}"
case "$mode" in
    --check|--update|--help) ;;
    *) echo "unknown arg: $mode"; exit 2 ;;
esac
if [ "$mode" = "--help" ]; then sed -n '2,25p' "$0"; exit 0; fi

# ── source 1: doctor.rs system_lib_check rows ────────────────────────────────
# Parse `system_lib_check("label", "pc", "linked_by", "apt"),` call sites.
doctor_rows=$(grep -o 'system_lib_check("[^"]*", "[^"]*", "[^"]*", "[^"]*")' "$DOCTOR" 2>/dev/null || true)
doctor_labels=$(printf '%s\n' "$doctor_rows" | sed 's/system_lib_check("\([^"]*\)".*/\1/' | sort -u)
doctor_count=$(printf '%s\n' "$doctor_rows" | grep -c . || true)

# ── source 2: musl APK_SET (informational apk column) ───────────────────────
apk_set=$(grep -o 'APK_SET="[^"]*"' "$MUSL_SH" 2>/dev/null | head -1 | sed 's/APK_SET="//; s/"$//' || true)

# ── source 3: links = declarations (manifest face) ──────────────────────────
links_rows=$(grep -rn 'links = "' src/*/Cargo.toml src/*/*/Cargo.toml 2>/dev/null | sed 's|^src/||; s|:links = | → |' || true)

# ── generate the document ────────────────────────────────────────────────────
gen_doc() {
    {
        echo "# Native Dependency Inventory (docs/native-deps.md)"
        echo
        echo "W23-③ single source of truth for the native-library contract."
        echo "Regenerated by \`scripts/native-deps-inventory.sh --update\`; the gate"
        echo "(\`--check\`) asserts the doctor↔doc diff = 0 in both directions."
        echo
        echo "## Runtime check face (doctor.rs \`system_lib_check\` — $doctor_count rows)"
        echo
        echo "| label | pkg-config | linked by | apt | apk (musl APK_SET) |"
        echo "|---|---|---|---|---|"
        printf '%s\n' "$doctor_rows" | while IFS= read -r row; do
            [ -z "$row" ] && continue
            label=$(printf '%s' "$row" | sed 's/system_lib_check("\([^"]*\)".*/\1/')
            pc=$(printf '%s' "$row" | sed 's/[^,]*, "\([^"]*\)".*/\1/')
            by=$(printf '%s' "$row" | sed 's/[^,]*, "[^"]*", "\([^"]*\)".*/\1/')
            apt=$(printf '%s' "$row" | sed 's/[^,]*, "[^"]*", "[^"]*", "\([^"]*\)")/\1/')
            # Debian (apt) and Alpine (apk) package names differ in shape —
            # the apk column defers to the musl APK_SET section below instead
            # of pretending an automatic name mapping.
            echo "| $label | $pc | $by | $apt | see musl face |"
        done
        echo
        echo "## musl face (musl-p5-consumer-closure.sh APK_SET — informational)"
        echo
        echo '```'
        echo "$apk_set"
        echo '```'
        echo
        echo "## Cargo manifest \`links\` face"
        echo
        if [ -n "$links_rows" ]; then printf '%s\n' "$links_rows" | sed 's/^/- `/; s/$/`/'; else echo "(none)"; fi
        echo
        echo "## Platform notes"
        echo
        echo "- macOS (brew): fontconfig/freetype/glib/gstreamer serve the same servo stack — names per the ci-slim matrix precedent (docs/platform-support.md)."
        echo "- Windows: native deps ride the vendored/clang-cl path (win-cross-env.sh); no pkg-config face."
        echo "- W23-③ boundary: doctor.rs is product code — this inventory never edits it; a gap is a RED for a separate fix contract."
    } > "$DOC"
    echo "[native-deps] doc regenerated: $DOC (doctor rows: $doctor_count)"
}

if [ "$mode" = "--update" ]; then
    gen_doc
    exit 0
fi

# ── --check gate: doctor ↔ doc bidirectional diff ────────────────────────────
[ -f "$DOC" ] || { echo "[native-deps] RED: $DOC missing — run --update first"; exit 1; }
rc=0
printf '%s\n' "$doctor_labels" | while IFS= read -r label; do
    [ -z "$label" ] && continue
    if ! grep -q "^| $label |" "$DOC"; then
        echo "[native-deps] RED: doctor row '$label' missing from $DOC"
        rc=1
    fi
done
# doc-side: every table row label must exist in doctor.rs
doc_labels=$(grep -o '^| [A-Za-z0-9 ().+-]* | ' "$DOC" | sed 's/^| //; s/ | $//' | sort -u)
printf '%s\n' "$doc_labels" | while IFS= read -r label; do
    [ -z "$label" ] && continue
    case "$label" in label|---*) continue ;; esac
    if ! printf '%s\n' "$doctor_labels" | grep -qxF "$label"; then
        echo "[native-deps] RED: doc row '$label' has no doctor.rs system_lib_check (stale doc or missing check)"
        rc=1
    fi
done
# subshell rc propagation via a marker file
mk=$(mktemp)
printf '%s\n' "$doctor_labels" | while IFS= read -r label; do
    [ -z "$label" ] && continue
    grep -q "^| $label |" "$DOC" || { echo "RED doctor→doc: $label" >> "$mk"; }
done
doc_labels=$(grep -o '^| [A-Za-z0-9 ().+-]* | ' "$DOC" | sed 's/^| //; s/ | $//' | sort -u)
printf '%s\n' "$doc_labels" | while IFS= read -r label; do
    [ -z "$label" ] && continue
    case "$label" in label) continue ;; esac
    printf '%s\n' "$doctor_labels" | grep -qxF "$label" || echo "RED doc→doctor: $label" >> "$mk"
done
if [ -s "$mk" ]; then
    cat "$mk" >&2
    rm -f "$mk"
    echo "[native-deps] GATE RED" >&2
    exit 1
fi
rm -f "$mk"
echo "[native-deps] GATE GREEN (doctor rows: $doctor_count; bidirectional diff = 0)"
