[package]
name = "bao_crypto"
version = "0.1.2"
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]
bun_boringssl_sys = { path = "../boringssl_sys", version = "0.1.0" }
hex = "0.4"
thiserror.workspace = true
