[package]
name = "bun_sha_hmac"
version = "0.1.3"
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[lib]
path = "lib.rs"

[lints]
workspace = true

[dependencies]
phf.workspace = true
bun_core.workspace = true
bun_boringssl.workspace = true
bun_boringssl_sys.workspace = true
