[package]
name = "bun_md"
version = "0.1.4"
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[lib]
path = "lib.rs"

[lints]
workspace = true

[dependencies]
pulldown-cmark.workspace = true
scopeguard.workspace = true
bun_alloc.workspace = true
bun_core.workspace = true
bun_collections.workspace = true
bun_sys.workspace = true
bun_url.workspace = true
bun_paths.workspace = true

[[test]]
name = "md_pulldown_cmark_tests"
path = "tests/md_pulldown_cmark_tests.rs"
