[package]
name = "bun_lolhtml_sys"
version = "0.1.2"
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[lib]
path = "lib.rs"

[lints]
workspace = true

[dependencies]
lol_html = "3.0"
bun_core.workspace = true
thiserror.workspace = true
