// Auto-generated build_options.rs for Bao development builds.
// In Bun upstream, this file is generated by scripts/build/buildOptionsRs.ts.

pub const SHA: &str = "0000000000000000000000000000000000000000";
pub const IS_CANARY: bool = false;
pub const CANARY_REVISION: &str = "";
pub const BASELINE: bool = false;
pub const RELEASE_SAFE: bool = false;
pub const ENABLE_LOGS: bool = false;
pub const ENABLE_ASAN: bool = false;
pub const ENABLE_FUZZILLI: bool = false;
pub const ENABLE_TINYCC: bool = false;
pub const REPORTED_NODEJS_VERSION: &str = "22.14.0";
pub const BASE_PATH: &[u8] = b"/usr/local";
pub const CODEGEN_PATH: &[u8] = b"build/debug/codegen";
pub const FALLBACK_HTML_VERSION: &str = "0.0.0-dev";
pub const VERSION: crate::Version = crate::Version {
    major: 0,
    minor: 0,
    patch: 0,
};
